misc fixes
carbon-design-system/carbon-for-ibm-dotcom-website pull request #1180
Opened 2021-09-13 14:00 UTC by shixiedesign

### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1178

### Description

### Changelog

**New**

- added a bit of guidance to Content block horizontal 

**Changed**

- Fixed links to `video-player` to `video`

**Removed**

- Button group page
- Removed links to `Feature card block` for now

2021-09-13 15:30 UTC, janchild reviewed
Lots of nice fixes on lots of pages here! I did a super detailed review and found some extra things too. Sorry should have used the `Edit file` option.

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
> +More more on character count,
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer">see
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
> +all character count standards</a>.
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
>  ### Dark themes (gray 100 or gray 90)
```suggestion
### Dark themes (Gray 100 or Gray 90)
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
> +Use `gray 100` or `gray 90` when the background image has shadows, is dimly lit,
```suggestion
Use `Gray 100` or `Gray 90` when the background image has shadows, is dimly lit,
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
>  ### Light themes (white or gray 10)
```suggestion
### Light themes (White or Gray 10)
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leadspace.mdx
> +Use `white` or `gray 10` when the background image is well-lit or brightly
```suggestion
Use `White` or `Gray 10` when the background image is well-lit or brightly
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/video.mdx
> +  The Video component allows you as an adopter to embed Kaltura videos from the
```suggestion
  The Video component allows you to embed Kaltura videos from the
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/video.mdx
> +you're using, you could also remove the prefilled content.
```suggestion
you're using, you can also remove the prefilled content.
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/callout-with-media.mdx
> +To see the list of all character count standards, go to this
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/callout-with-media.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer noopener nofollow">link</a>.
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-horizontal.mdx
> +To see the list of all character count standards, go to this
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-horizontal.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer noopener nofollow">link</a>.
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-media.mdx
> +You can see the list of all character count standards
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-media.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer">here</a>.
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-segmented.mdx
> +To see the list of all character count standards, go to this
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-segmented.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer">link</a>.
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-simple.mdx
> +To see the list of all character count standards, go to this
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-block-simple.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer noopener nofollow">link</a>.
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-group-simple.mdx
> +To see the list of all character count standards, go to this
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/content-group-simple.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer">link</a>.
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/cta-section.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer">link</a>.
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/cta-section.mdx
> +To see the list of all character count standards, go to this
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/lead-space-block.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank">link</a>.
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/lead-space-block.mdx
> +To see the list of all character count standards, go to this
```suggestion
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/leaving-ibm.mdx
> +  The Leaving IBM displays as an overlay when users click an external link icon.
```suggestion
  The Leaving IBM notice displays as an overlay when users click an external link icon.
```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/video.mdx
> +<a href="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards" target="_blank" rel="noreferrer noopener nofollow">link</a>.
```suggestion
For more information, see the [character count standards](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards).

```

2021-09-13 15:30 UTC, janchild commented on src/pages/components/video.mdx
> +To see the list of all character count standards, go to this
```suggestion
```

2021-09-13 16:21 UTC, JBrandwine requested changes
a good component for presenting a large amount of CTAs with context.

2021-09-13 16:21 UTC, JBrandwine commented on src/pages/components/content-block-horizontal.mdx
> +a good component for presenting large amount of CTAs with context. Please note
a good component for presenting large amount of CTAs with context.

2021-09-13 18:14 UTC, janchild reviewed
@shixiedesign I noticed that the .yaml file wasn't updated in the preview. Not sure if it's a caching issue. But I noticed the component name needed an update, so just two more changes here.

2021-09-13 18:14 UTC, janchild commented on src/data/nav-items.yaml
>      - title: Leaving IBM
```suggestion
    - title: Leaving IBM modal
```

2021-09-13 18:14 UTC, janchild commented on src/data/components.json
>      "Leaving IBM": {
```suggestion
    "Leaving IBM modal": {
```

2021-09-14 13:32 UTC, JBrandwine approved these changes
Content block horizontal text looks good, updated link to video component validated on callout with media, button group page not present in left nav.

Thanks!

2021-09-14 14:12 UTC, janchild approved these changes
🧗‍♀️ 🥂

2021-09-14 15:56 UTC, merged