Docs  footnote page
carbon-design-system/carbon-for-ibm-dotcom-website pull request #1431
Opened 2022-01-12 20:23 UTC by RichKummer

### Related Ticket(s)

[#7705](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7705)

### Description

Added a new page for Footnote section containing an overview and anatomy section.

### Changelog

**New**

- New Footnote section page

**Changed**

- Updated yaml file with new page in navigation

**Removed**

- N/A

2022-01-12 22:43 UTC, oliviaflory requested changes
Made some inline comments on the .json file

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "stable": true,
```suggestion
        "stable": false,
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "updated": true,
```suggestion
        "updated": false,
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "underConstruction": false,
```suggestion
        "underConstruction": true,
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "stable": true,
```suggestion
        "stable": false,
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "updated": true,
```suggestion
        "updated": false,
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "underConstruction": false,
```suggestion
        "underConstruction": true,
```
I'm guessing they will do a react wrapper for this

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "webcomponents": "http://www.ibm.com/standards/carbon/web-components/?path=/story/components-footer--default",
```suggestion
        "webcomponents": "",
```

2022-01-12 22:43 UTC, oliviaflory commented on src/data/components.json
> +        "react": "http://www.ibm.com/standards/carbon/react/?path=/story/components-footer--default"
```suggestion
        "react": ""
```

2022-01-12 22:51 UTC, oliviaflory commented
A few things I noticed that we could chat about tomorrow in Huddle:
1. `Footnote section` is throwing me off a bit because all of our `section` components have a Content section title, but we eliminated that bit.. 
2. Overview image: I think it might be helpful to show the overview in the context of a browser using the image production guidelines and the footer below it.
3. Anatomy: Let's add in the optional border to the anatomy spec / list

It might be good to talk about that the list and adjunct information can accommodate links. Can the author/user select just part of the footnote for the link or is the whole thing clickable?

We might want to reference the adjunct links in the footer as well and when to choose the Footnotes vs Footer to house those.

2022-01-14 00:25 UTC, RichKummer commented
Made an update to images on the page, but only updated for 2 and 3. 1 and 4 pending

2022-01-21 17:50 UTC, closed without merging